// <auto-generated />
using System;
using Infrastructure.Persistency;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209233709_ImageSeeding")]
    partial class ImageSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pequeñas porciones para abrir el apetito antes del plato principal.",
                            Name = "Entradas",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Opciones frescas y livianas, ideales como acompañamiento o plato principal.",
                            Name = "Ensaladas",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Platos rápidos, y clásicos de bodegón: milanesas, tortillas, revueltos.",
                            Name = "Minutas",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Variedad de pastas caseras y salsas tradicionales.",
                            Name = "Pastas",
                            Order = 5
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cortes de carne asados a la parrilla, servidos con guarniciones.",
                            Name = "Parrilla",
                            Order = 4
                        },
                        new
                        {
                            Id = 6,
                            Description = "Pizzas artesanales con masa ccasera y variedad de ingredientes.",
                            Name = "Pizzas",
                            Order = 7
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sandwiches y lomitos completos preparados al momento.",
                            Name = "Sandwiches",
                            Order = 6
                        },
                        new
                        {
                            Id = 8,
                            Description = "Gaseosas, jugos, aguas y opciones sin alcohol.",
                            Name = "Bebidas",
                            Order = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cervezas de producción artesanal, rubias, rojas y negras.",
                            Name = "Cerveza Artesanal",
                            Order = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "Clásicos dulces caseros para cerrar la comida.",
                            Name = "Postres",
                            Order = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.DeliveryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Delivery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Take away"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dine in"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Dish", b =>
                {
                    b.Property<Guid>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DishId");

                    b.HasIndex("Category");

                    b.ToTable("Dish", (string)null);

                    b.HasData(
                        new
                        {
                            DishId = new Guid("11111111-1111-1111-1111-111111111101"),
                            Available = true,
                            Category = 1,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clásica empanada frita rellena de carne cortada a cuchillo, huevo y cebolla de verdeo.",
                            ImageUrl = "https://images.unsplash.com/photo-1619926340139-9a2e2245a64e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZW1wYW5hZGElMjBhcmdlbnRpbmF8ZW58MHx8MHx8fDA%3D",
                            Name = "Empanada de Carne Cortada a Cuchillo",
                            Price = 1500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("11111111-1111-1111-1111-111111111102"),
                            Available = true,
                            Category = 1,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Queso provolone fundido a la parrilla con orégano, aceite de oliva y rodajas de tomate asado.",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0097/7892/1572/files/SvRumKBuh_2000x1500__1.jpg?v=1741958041",
                            Name = "Provoleta Especial",
                            Price = 6500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("11111111-1111-1111-1111-111111111103"),
                            Available = true,
                            Category = 1,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Anillos de calamar rebozados y fritos, servidos con limón y salsa tártara.",
                            ImageUrl = "https://www.clarin.com/img/2025/03/04/VN1snF0v2_1256x620__2.jpg#1741097857035",
                            Name = "Rabas a la Romana",
                            Price = 9000.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Available = true,
                            Category = 2,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lechuga fresca, croutons, queso parmesano en hebras, pechuga de pollo grillada y aderezo Caesar.",
                            ImageUrl = "https://plus.unsplash.com/premium_photo-1700089483464-4f76cc3d360b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c2FsYWQlMjBjYWVzYXJ8ZW58MHx8MHx8fDA%3D",
                            Name = "Ensalada Caesar con Pollo",
                            Price = 7800.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Available = true,
                            Category = 2,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hojas de rúcula selvática, tomates secos hidratados y láminas de queso parmesano.",
                            ImageUrl = "https://imag.bonviveur.com/ensalada-de-rucula_1000.webp",
                            Name = "Ensalada de Rúcula y Parmesano",
                            Price = 7200.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("33333333-3333-3333-3333-333333333301"),
                            Available = true,
                            Category = 3,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Milanesa de ternera cubierta con salsa de tomate, jamón y abundante muzzarella. Acompañada de papas bastón.",
                            ImageUrl = "https://www.lanacion.com.ar/resizer/v2/milanesa-a-la-napolitana-con-guarnicion-de-papas-VLWFAANIWBGPFO4CSUHS7RYVVQ.jpg?auth=335fda04cf2733e39d11ca0ba979c1d0a8a55e6cdec15e4d5b00cfd59fbf9ed8&width=880&height=586&quality=70&smart=true",
                            Name = "Milanesa a la Napolitana con Fritas",
                            Price = 11500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("33333333-3333-3333-3333-333333333302"),
                            Available = true,
                            Category = 3,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tortilla de papas con cebolla y chorizo colorado. Punto babé.",
                            ImageUrl = "https://www.lanacion.com.ar/resizer/v2/tortilla-de-OGZW2PTYC5G6BESKCCDVFU3SDA.jpg?auth=3fba4327702c5439286db1f399c437a61c2c77afba59e23816800e6ceb27e85f&width=880&height=586&quality=70&smart=true",
                            Name = "Tortilla de Papas Española",
                            Price = 8500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("33333333-3333-3333-3333-333333333303"),
                            Available = true,
                            Category = 3,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suprema de pollo con salsa de choclo, banana frita y papas pay.",
                            ImageUrl = "url_maryland",
                            Name = "Suprema Maryland",
                            Price = 12000.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("44444444-4444-4444-4444-444444444401"),
                            Available = true,
                            Category = 4,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sorrentinos caseros rellenos de jamón cocido y muzzarella con salsa a elección (Fileto, Crema o Mixta).",
                            ImageUrl = "url_sorrentinos",
                            Name = "Sorrentinos de Jamón y Queso",
                            Price = 9500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("44444444-4444-4444-4444-444444444402"),
                            Available = true,
                            Category = 4,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Los clásicos del 29. Ñoquis de papa servidos con estofado de carne.",
                            ImageUrl = "url_noquis",
                            Name = "Ñoquis de Papa Caseros",
                            Price = 8900.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("55555555-5555-5555-5555-555555555501"),
                            Available = true,
                            Category = 5,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Costillar de ternera cortado transversalmente, asado a fuego lento. Incluye guarnición.",
                            ImageUrl = "url_asado",
                            Name = "Asado de Tira",
                            Price = 14500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("55555555-5555-5555-5555-555555555502"),
                            Available = true,
                            Category = 5,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Corte ancho y jugoso de bife de chorizo, punto a elección.",
                            ImageUrl = "url_bife_chorizo",
                            Name = "Bife de Chorizo (400g)",
                            Price = 16000.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("55555555-5555-5555-5555-555555555503"),
                            Available = true,
                            Category = 5,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Matambre de ternera tierno con salsa de tomate y queso muzzarella, finalizado a la parrilla.",
                            ImageUrl = "url_matambre",
                            Name = "Matambre a la Pizza",
                            Price = 15500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("66666666-6666-6666-6666-666666666601"),
                            Available = true,
                            Category = 6,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Salsa de tomate casera, abundante muzzarella, orégano y aceitunas verdes.",
                            ImageUrl = "url_pizza_muzza",
                            Name = "Pizza Muzzarella Grande",
                            Price = 8000.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("66666666-6666-6666-6666-666666666602"),
                            Available = true,
                            Category = 6,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Muzzarella, jamón cocido natural y tiras de morrones asados.",
                            ImageUrl = "url_pizza_especial",
                            Name = "Pizza Especial con Jamón y Morrones",
                            Price = 9500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("77777777-7777-7777-7777-777777777701"),
                            Available = true,
                            Category = 7,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lomo de ternera en pan francés con lechuga, tomate, jamón, queso y huevo frito. Sale con papas.",
                            ImageUrl = "url_lomito",
                            Name = "Lomito Completo",
                            Price = 10500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("77777777-7777-7777-7777-777777777702"),
                            Available = true,
                            Category = 7,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Doble medallón de carne (240g), doble cheddar, panceta crocante y cebolla caramelizada.",
                            ImageUrl = "url_hamburguesa",
                            Name = "Hamburguesa Doble Cheddar",
                            Price = 9800.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("88888888-8888-8888-8888-888888888801"),
                            Available = true,
                            Category = 8,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Línea Coca-Cola o Pepsi según disponibilidad.",
                            ImageUrl = "url_gaseosa",
                            Name = "Gaseosa Cola 500ml",
                            Price = 2500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("88888888-8888-8888-8888-888888888802"),
                            Available = true,
                            Category = 8,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Villavicencio o Eco de los Andes.",
                            ImageUrl = "url_agua",
                            Name = "Agua Mineral sin Gas 500ml",
                            Price = 2200.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("99999999-9999-9999-9999-999999999901"),
                            Available = true,
                            Category = 9,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cerveza Indian Pale Ale, amargor intenso y notas cítricas.",
                            ImageUrl = "url_ipa",
                            Name = "Pinta IPA",
                            Price = 4500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("99999999-9999-9999-9999-999999999902"),
                            Available = true,
                            Category = 9,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cerveza rubia suave con un toque de miel.",
                            ImageUrl = "url_honey",
                            Name = "Pinta Honey",
                            Price = 4500.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01"),
                            Available = true,
                            Category = 10,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Flan de huevo tradicional acompañado de dulce de leche y crema chantilly.",
                            ImageUrl = "url_flan",
                            Name = "Flan Casero Mixto",
                            Price = 4200.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DishId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02"),
                            Available = true,
                            Category = 10,
                            CreateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Panqueque tibio relleno con abundante dulce de leche repostero.",
                            ImageUrl = "url_panqueque",
                            Name = "Panqueque de Dulce de Leche",
                            Price = 4000.00m,
                            UpdateDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryTo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<int>("OverallStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("DeliveryType");

                    b.HasIndex("OverallStatus");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.Property<long>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderItemId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Dish")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("Dish");

                    b.HasIndex("Order");

                    b.HasIndex("Status");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "In progress"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ready"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Delivery"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Closed"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Dish", b =>
                {
                    b.HasOne("Domain.Entities.Category", "CategoryNav")
                        .WithMany("Dishes")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Dish_Category_Category");

                    b.Navigation("CategoryNav");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.DeliveryType", "DeliveryTypeNav")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Status", "OverallStatusNav")
                        .WithMany("Orders")
                        .HasForeignKey("OverallStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryTypeNav");

                    b.Navigation("OverallStatusNav");
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.Dish", "DishNav")
                        .WithMany("OrderItems")
                        .HasForeignKey("Dish")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Order", "OrderNav")
                        .WithMany("OrderItems")
                        .HasForeignKey("Order")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Status", "StatusNav")
                        .WithMany("OrderItems")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DishNav");

                    b.Navigation("OrderNav");

                    b.Navigation("StatusNav");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("Domain.Entities.DeliveryType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Dish", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.Status", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
